
export const allModels = [
  {
    id: 1,
    name: "Alexandre",
    age: 24,
    height: "6'2\"",
    hairColor: "Blonde",
    bodyType: "Athletic",
    expertise: "Runway",
    location: "Paris",
    specialty: "High Fashion",
    imageUrl: "/images/models/alexandre-profile.jpg",
    portfolio: [
      { id: 1, url: "/images/models/alexandre-portfolio-1.jpg", alt: "Alexandre runway shot", hint: "male model runway"},
      { id: 2, url: "/images/models/alexandre-portfolio-2.jpg", alt: "Alexandre editorial", hint: "male model editorial" },
      { id: 3, url: "/images/models/alexandre-portfolio-3.jpg", alt: "Alexandre commercial", hint: "male model commercial" },
      { id: 4, url: "/images/models/alexandre-portfolio-4.jpg", alt: "Alexandre portrait", hint: "male model portrait" },
    ],
  },
  {
    id: 2,
    name: "Javier",
    age: 28,
    height: "6'1\"",
    hairColor: "Brown",
    bodyType: "Lean",
    expertise: "Editorial",
    location: "Milan",
    specialty: "Print & Editorial",
    imageUrl: "/images/models/javier-profile.jpg",
    portfolio: [
      { id: 1, url: "/images/models/javier-portfolio-1.jpg", alt: "Javier cover shoot", hint: "male model magazine" },
      { id: 2, url: "/images/models/javier-portfolio-2.jpg", alt: "Javier lifestyle", hint: "male model lifestyle" },
    ],
  },
  {
    id: 3,
    name: "Kenji",
    age: 21,
    height: "6'0\"",
    hairColor: "Black",
    bodyType: "Slim",
    expertise: "Commercial",
    location: "Tokyo",
    specialty: "Commercial & Print",
    imageUrl: "/images/models/kenji-profile.jpg",
    portfolio: [
      { id: 1, url: "/images/models/kenji-portfolio-1.jpg", alt: "Kenji ad campaign", hint: "male model advertising" },
      { id: 2, url: "/images/models/kenji-portfolio-2.jpg", alt: "Kenji studio shot", hint: "male model studio" },
      { id: 3, url: "/images/models/kenji-portfolio-3.jpg", alt: "Kenji portrait", hint: "male model urban" },
    ],
  },
  {
    id: 4,
    name: "Liam",
    age: 30,
    height: "6'3\"",
    hairColor: "Red",
    bodyType: "Muscular",
    expertise: "Fitness",
    location: "New York",
    specialty: "Fitness & Sport",
    imageUrl: "/images/models/liam-profile.jpg",
    portfolio: [
      { id: 1, url: "/images/models/liam-portfolio-1.jpg", alt: "Liam fitness shoot", hint: "male model fitness" },
      { id: 2, url: "/images/models/liam-portfolio-2.jpg", alt: "Liam sportswear ad", hint: "male model sportswear" },
    ],
  },
    {
    id: 5,
    name: "Mateo",
    age: 26,
    height: "6'1\"",
    hairColor: "Brown",
    bodyType: "Athletic",
    expertise: "Commercial",
    location: "Los Angeles",
    specialty: "Lifestyle & Commercial",
    imageUrl: "/images/models/mateo-profile.jpg",
    portfolio: [],
  },
  {
    id: 6,
    name: "Chen",
    age: 22,
    height: "6'0\"",
    hairColor: "Black",
    bodyType: "Lean",
    expertise: "Runway",
    location: "Shanghai",
    specialty: "Avant-Garde",
    imageUrl: "/images/models/chen-profile.jpg",
    portfolio: [],
  },
  {
    id: 7,
    name: "David",
    age: 29,
    height: "6'2\"",
    hairColor: "Blonde",
    bodyType: "Muscular",
    expertise: "Fitness",
    location: "London",
    specialty: "Underwear & Fitness",
    imageUrl: "/images/models/david-profile.jpg",
    portfolio: [],
  },
  {
    id: 8,
    name: "Thiago",
    age: 25,
    height: "6'1\"",
    hairColor: "Brown",
    bodyType: "Slim",
    expertise: "Editorial",
    location: "São Paulo",
    specialty: "Indie Fashion",
    imageUrl: "/images/models/thiago-profile.jpg",
    portfolio: [],
  },
];

export const featuredModels = allModels.slice(0, 4);

export const blogPosts = [
  {
    slug: "nyfw-fall-2024-recap",
    title: "NYFW Fall 2024: Our Models Dominate the Runway",
    excerpt: "From emerging designers to established houses, eMM models were the talk of New York Fashion Week. Get a behind-the-scenes look at the shows, the after-parties, and the moments that defined the week.",
    content: "<p>The air in New York was electric, and it wasn't just the autumn chill. New York Fashion Week Fall 2024 was a spectacle of innovation, style, and raw talent, and we are incredibly proud that ecHe Male Models International was at the very heart of it. Our models, including the indomitable Alexandre and newcomer Chen, graced the runways for some of the most anticipated shows of the season.</p><p>Alexandre opened for the critically acclaimed show, a testament to his powerful presence and versatility. Meanwhile, Chen made a stunning debut, with critics praising his unique look and confident walk. This season was all about pushing boundaries, and our models did just that, showcasing collections that ranged from avant-garde to timelessly elegant.</p>",
    author: "Agency Staff",
    date: "2024-09-18",
  },
  {
    slug: "art-of-the-pose-javier",
    title: "The Art of the Pose: A Masterclass with Javier",
    excerpt: "Go on set with our editorial star, Javier, as he shares his secrets to capturing the perfect shot. A must-read for aspiring models and photographers alike.",
    content: "<p>What makes a good photograph great? For Javier, it's all in the subtleties. We spent a day on set with the editorial powerhouse for his latest cover shoot. Between shots, he shared insights into his process. 'It's a dance with the camera,' he explained. 'You have to understand the light, the clothes, the mood. Every element tells a part of the story.' This article delves into his techniques for conveying emotion and narrative through stillness.</p>",
    author: "Guest Contributor",
    date: "2024-08-25",
  },
  {
    slug: "fitness-modeling-with-liam",
    title: "More Than Muscle: The Discipline of Fitness Modeling with Liam",
    excerpt: "It takes more than a great physique to succeed in fitness modeling. Liam discusses the diet, training, and mental fortitude required to stay at the top of his game.",
    content: "<p>For Liam, fitness modeling is a 24/7 commitment. 'The gym is only part of it,' he says. 'What you eat, how you rest, your mental state—it's a holistic lifestyle.' We followed Liam through a typical day, from his 5 AM workout to his meticulously planned meals. He offers a candid look at the dedication behind the images, providing inspiration and practical advice for anyone in the fitness world.</p>",
    author: "Agency Staff",
    date: "2024-07-12",
  },
];
